### PR TITLE
Port to Firefox

### PR DESCRIPTION
**Pull request by jazzzz**

### CODE REVIEW

**Comment by nicolasmaia** [comment]
@tankaru Any issues with the PR?

**Comment by tankaru** [comment]
@picsi 
I haven't tried it.
Have you tried the port by jazzzz? How was that?

**Comment by nicolasmaia** [comment]
I haven't tried it either, I was waiting for this to be merged 😝

**Comment by jazzzz** [comment]
@tankaru do you have some examples where I could test this extension?

**Comment by tankaru** [comment]
@jazzzz Here is an example web page (map of Golden gate bridge).
https://en.support.wordpress.com/google-maps/

**Comment by jazzzz** [comment]
> @jazzzz Here is an example web page (map of Golden gate bridge).
> https://en.support.wordpress.com/google-maps/

It works in both Chrome and Firefox :+1:

**Pull request merged**
